**Import Library**

### ***Install Library***

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 4.3 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [4]:
#scraper all available reviews
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
'com.google.android.youtube',
lang='id',
country='id',
sort=Sort.NEWEST,
count=10000,
filter_score_with=None
)

**Show Data yang sudah di crawling**

In [5]:
df_busu = pd.DataFrame(np.array(result),columns=['review']) #nama file bebas
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,5be1817d-bbb5-45c1-9070-387ebf24eb6e,Kusrsih Hadikusuma,https://play-lh.googleusercontent.com/a/ACg8oc...,Kenapa makin kesini aplikasi ini bikin kesal g...,5,0,12.37.59,2026-05-18 19:41:19,None,None,12.37.59
9996,1ba79de3-1081-4643-a778-06b564592cde,Jajang Suryaman,https://play-lh.googleusercontent.com/a/ACg8oc...,sehat,4,0,21.19.286,2026-05-18 19:19:48,None,None,21.19.286
9997,3425ba51-fd40-4333-89b0-5390b35cf40f,Gibran123 Jedor,https://play-lh.googleusercontent.com/a/ACg8oc...,bgus,5,0,13.07.55,2026-05-18 19:16:44,None,None,13.07.55
9998,f653a8ab-c88f-4691-82e3-4962c77e5f4a,Muhammad Habib,https://play-lh.googleusercontent.com/a-/ALV-U...,kenapa saat ini YouTube punya peraturan yg tid...,1,0,13.07.55,2026-05-18 18:26:35,None,None,13.07.55
9999,40383ed1-43ad-4bba-90f7-98eb2d1ea0c8,Cerita 1 Menit,https://play-lh.googleusercontent.com/a-/ALV-U...,"bro, gua bangun channel dari 0, sampai sekaran...",1,0,21.16.245,2026-05-18 18:24:41,None,None,21.16.245

In [6]:
len(df_busu.index)

10000

**Ambil data yang dibutuhkan**

In [7]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,Kusrsih Hadikusuma,5,2026-05-18 19:41:19,Kenapa makin kesini aplikasi ini bikin kesal g...
9996,Jajang Suryaman,4,2026-05-18 19:19:48,sehat
9997,Gibran123 Jedor,5,2026-05-18 19:16:44,bgus
9998,Muhammad Habib,1,2026-05-18 18:26:35,kenapa saat ini YouTube punya peraturan yg tid...
9999,Cerita 1 Menit,1,2026-05-18 18:24:41,"bro, gua bangun channel dari 0, sampai sekaran..."

In [8]:
my_df= df_busu[['userName', 'score', 'at', 'content']]

In [9]:
#simpan dataset ke dalam file
my_df.to_csv("Dataset_YouTube.csv", index=False)