In [12]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [13]:
#untuk komputasi numerik
import numpy as pd

#memproses pengolahan text (Natural Language Toolkit)
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola kata spesifik yang dicari (Regular Expression - Regex)
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

In [14]:
#import Library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_column', None)
pd.pandas.set_option('display.max_row', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [15]:
df = pd.read_csv('/content/Dataset_YouTube (1).csv')
df.head()

,userName,score,at,content
0,Pengguna Google,5,2026-06-08 05:10:15,sangat bagus aplikasi ini saya sangat suka
1,Pengguna Google,5,2026-06-08 05:06:44,"Fgz,"
2,Pengguna Google,5,2026-06-08 05:06:31,susah lelet
3,Pengguna Google,4,2026-06-08 05:03:40,you tube
4,Pengguna Google,5,2026-06-08 05:00:20,PP apa dia sungguh mempesona UU apa ...

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   userName  10000 non-null  object
 1   score     10000 non-null  int64
 2   at        10000 non-null  object
 3   content   10000 non-null  object
dtypes: int64(1), object(3)
memory usage: 312.6+ KB

In [17]:
df['sentiment'] = df['score'].map({1.0:0, 2.0:0, 3.0:1, 4.0:1, 5.0:1})

In [18]:
#Ambil teks aja untuk kita labelkan
dataku = pd.DataFrame(df[['content', 'sentiment']])
dataku.head(10)

                                                          content  sentiment
0                      sangat bagus aplikasi ini saya sangat suka          1
1                                                            Fgz,          1
2                                                     susah lelet          1
3                                                        you tube          1
4                         PP apa dia sungguh mempesona UU apa ...          1
5                       Ko h kkb gj id gu Chkv b Cgk n H go if vv          0
6                                                           Bagus          1
7                                                          Senang          1
8                                      saya gak bisa buka yuotube          1
9  banyak iklan 1 video bisa 7 iklan gw post di tahun 2026 8 juni          0

In [19]:
my_df = dataku[['content', 'sentiment']]

In [20]:
#simpan Dataset ke dalam file
my_df.to_csv("label_youtube.csv", index = False)